import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "surface-tint": "#106d20",
        "on-surface-variant": "#40493d",
        "surface-variant": "#d3e4fe",
        background: "#f8f9ff",
        "tertiary-fixed-dim": "#ffb1c8",
        error: "#ba1a1a",
        outline: "#707a6c",
        "secondary-fixed": "#d8e3fb",
        "outline-variant": "#bfcab9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#822049",
        primary: "#0b6b1d",
        "on-secondary-fixed-variant": "#3c475a",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "on-primary-container": "#f7fff1",
        "secondary-container": "#d5e0f8",
        "on-primary-fixed-variant": "#005312",
        "tertiary-fixed": "#ffd9e2",
        "on-secondary": "#ffffff",
        secondary: "#545f73",
        "on-tertiary-container": "#fffbff",
        "primary-fixed": "#9df898",
        "secondary-fixed-dim": "#bcc7de",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#82db7e",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed": "#111c2d",
        "primary-container": "#2e8534",
        "on-tertiary-fixed": "#3e001d",
        "surface-container-lowest": "#ffffff",
        tertiary: "#9d365f",
        "inverse-primary": "#82db7e",
        surface: "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed": "#002204",
        "on-secondary-container": "#586377",
        "on-primary": "#ffffff",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "tertiary-container": "#bc4f77",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        sm: "8px",
        unit: "8px",
        lg: "24px",
        "container-max": "1280px",
        gutter: "24px",
        xl: "32px",
        xs: "4px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
